image: node:latest

variables:
  GIT_STRATEGY: none
  GITHUB_REPO: "https://oauth2:${GITHUB_TOKEN}@github.com/Gangasaikumar/SimpleCalculator.git"

before_script:
  - echo "Cloning latest code..."
  - git clone $GITHUB_REPO .
  - git checkout main
  - npm ci

stages:
  - test
  - build

lint_code:
  stage: test
  script:
    - npm run lint

unit_tests:
  stage: test
  script:
    - npm run test:coverage
  artifacts:
    when: always
    paths:
      - coverage/
      - junit.xml

build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
